name: CI pipeline

on:
  pull_request:
    branches:
      - main
    tags-ignore:
      - 'v*' # this tag type is used for release pipelines

jobs:
  ci-pipeline:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    env:
      DATABRICKS_HOST: https://adb-3491128444128477.17.azuredatabricks.net
      DATABRICKS_TOKEN:  dapi54d86fa75b379de604f7bc20727ee49f

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9.6

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies and project in dev mode
        run: |
          pip install -r unit-requirements.txt
          pip install -e .

      - name: Run unit tests
        run: |
          echo "Launching unit tests"
          pytest tests/unit

      - name: Deploy integration test [staging environment]
        run: |
          dbx deploy --jobs=STAGING-telco-churn-sample-integration-test --environment=staging --files-only

      - name: Run integration test [staging environment]
        run: |
          dbx launch --job=STAGING-telco-churn-sample-integration-test --environment=staging --as-run-submit --trace